# Generated by Django 5.2.1 on 2025-09-27 01:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_appointments', models.IntegerField(default=0)),
                ('completed_appointments', models.IntegerField(default=0)),
                ('cancelled_appointments', models.IntegerField(default=0)),
                ('new_patients', models.IntegerField(default=0)),
                ('returning_patients', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('average_appointment_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('patient_satisfaction_score', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Business Analytics',
                'db_table': 'business_analytics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PatientAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_appointments', models.IntegerField(default=0)),
                ('completed_appointments', models.IntegerField(default=0)),
                ('cancelled_appointments', models.IntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_visit', models.DateTimeField(blank=True, null=True)),
                ('average_visit_frequency', models.IntegerField(default=0, help_text='Days between visits')),
                ('preferred_services', models.JSONField(blank=True, default=list)),
                ('risk_score', models.FloatField(default=0, help_text='Churn risk score (0-1)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Patient Analytics',
                'db_table': 'patient_analytics',
            },
        ),
        migrations.CreateModel(
            name='PatientSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment', models.CharField(choices=[('high_value', 'High Value'), ('frequent', 'Frequent'), ('occasional', 'Occasional'), ('at_risk', 'At Risk'), ('new', 'New')], max_length=20)),
                ('segment_score', models.FloatField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Patient Segments',
                'db_table': 'patient_segments',
            },
        ),
        migrations.CreateModel(
            name='ServiceAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_bookings', models.IntegerField(default=0)),
                ('completed_bookings', models.IntegerField(default=0)),
                ('cancelled_bookings', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('average_rating', models.FloatField(default=0)),
                ('popularity_score', models.FloatField(default=0)),
                ('seasonal_trends', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='services.service')),
            ],
            options={
                'verbose_name_plural': 'Service Analytics',
                'db_table': 'service_analytics',
            },
        ),
        migrations.CreateModel(
            name='TreatmentCorrelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlation_strength', models.FloatField(help_text='Correlation coefficient (-1 to 1)')),
                ('frequency', models.IntegerField(default=0, help_text='Number of times these services were booked together')),
                ('confidence_score', models.FloatField(default=0, help_text='Statistical confidence (0-1)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('primary_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_correlations', to='services.service')),
                ('secondary_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_correlations', to='services.service')),
            ],
            options={
                'verbose_name_plural': 'Treatment Correlations',
                'db_table': 'treatment_correlations',
                'unique_together': {('primary_service', 'secondary_service')},
            },
        ),
    ]
