# Generated by Django 5.2.1 on 2025-11-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('treatment_pattern', 'Treatment Pattern'), ('efficiency', 'Treatment Efficiency'), ('product_usage', 'Product Usage'), ('duration_analysis', 'Duration Analysis'), ('follow_up', 'Follow-up Recommendation'), ('health_score', 'Health Score'), ('trend', 'Trend Analysis')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='Detailed insight description')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('metrics', models.JSONField(blank=True, default=dict, help_text='Associated metrics and data')),
                ('recommendations', models.JSONField(blank=True, default=list, help_text='List of recommendations')),
                ('affected_treatments_count', models.IntegerField(default=0, help_text='Number of treatments analyzed')),
                ('affected_patients_count', models.IntegerField(default=0, help_text='Number of patients affected')),
                ('confidence_score', models.FloatField(default=0, help_text='Confidence in the insight (0-1)')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this insight is still relevant')),
            ],
            options={
                'verbose_name': 'Diagnosis',
                'verbose_name_plural': 'Diagnoses',
                'db_table': 'diagnoses',
                'ordering': ['-generated_at', '-severity'],
                'indexes': [models.Index(fields=['insight_type', 'is_active'], name='diagnoses_insight_e54173_idx'), models.Index(fields=['severity', 'generated_at'], name='diagnoses_severit_0c818c_idx')],
            },
        ),
    ]
