# Generated by Django 5.2.8 on 2025-11-27 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_diagnosis'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Diagnosis',
        ),
    ]
