# Generated by Django 5.2.1 on 2025-11-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
