# Generated by Django 5.2.1 on 2025-11-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_service_image_alter_serviceimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serviceimage',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
