# Generated by Django 5.2.1 on 2025-11-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_service_archived_serviceimage_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceimage',
            name='archived',
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='image',
            field=models.ImageField(upload_to='services/images/'),
        ),
    ]
