# Generated by Django 5.2.7 on 2025-11-12 01:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_reset_token_user_reset_token_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='reset_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='reset_token_created',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.CreateModel(
            name='AttendantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_days', models.JSONField(default=list, help_text="List of work days (e.g., ['Monday', 'Tuesday', ...])")),
                ('start_time', models.TimeField(default='10:00', help_text='Work start time (e.g., 10:00 AM)')),
                ('end_time', models.TimeField(default='18:00', help_text='Work end time (e.g., 6:00 PM)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'attendant'}, on_delete=django.db.models.deletion.CASCADE, related_name='attendant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'attendant_profiles',
            },
        ),
    ]
