# Generated by Django 5.2.1 on 2025-11-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendant',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
