# Generated by Django 5.2.8 on 2025-11-14 14:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_attendant_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendantprofile',
            name='phone',
            field=models.CharField(blank=True, help_text='11-digit phone number starting with 09', max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 11 digits starting with 09 (e.g., 09123456789).', regex='^09\\d{9}$')]),
        ),
    ]
