# Generated by Django 5.2.8 on 2025-11-15 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_add_phone_to_attendant_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendantLeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_date', models.DateField(help_text='Single day for which leave is requested')),
                ('reason', models.TextField(help_text='Reason for leave request (e.g., sick leave, personal emergency)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When the leave request was approved/rejected', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection, if rejected', null=True)),
                ('attendant_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='accounts.attendantprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Owner who approved/rejected the request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_leave_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'attendant_leave_requests',
                'ordering': ['-leave_date'],
                'unique_together': {('attendant_profile', 'leave_date')},
            },
        ),
    ]
