# Generated by Django 5.2.8 on 2025-11-27 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_attendant_archived_user_address_user_birthday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendant',
            name='archived',
        ),
    ]
