# Generated by Django 5.2.1 on 2025-09-20 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_closedday'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
