# Generated by Django 5.2.1 on 2025-10-26 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_transaction_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='closedday',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='closedday',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='closedday',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name='closedday',
            table='closed_days',
        ),
        migrations.CreateModel(
            name='SMSHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('pending', 'Pending')], default='sent', max_length=20)),
                ('message_id', models.CharField(blank=True, max_length=100, null=True)),
                ('api_response', models.JSONField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_sms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SMS History',
                'verbose_name_plural': 'SMS Histories',
                'db_table': 'sms_history',
                'ordering': ['-sent_at'],
            },
        ),
    ]
