# Generated by Django 5.2.1 on 2025-10-26 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_closedday_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Template name for easy identification', max_length=100)),
                ('template_type', models.CharField(choices=[('confirmation', 'Appointment Confirmation'), ('reminder', 'Appointment Reminder'), ('cancellation', 'Cancellation Notification'), ('package_confirmation', 'Package Confirmation'), ('custom', 'Custom Template')], max_length=30)),
                ('subject', models.CharField(blank=True, help_text='Optional subject line', max_length=200)),
                ('message', models.TextField(help_text='Message template with variables like {patient_name}, {appointment_date}, {appointment_time}, {service_name}')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_sms_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SMS Template',
                'verbose_name_plural': 'SMS Templates',
                'db_table': 'sms_templates',
                'ordering': ['template_type', 'name'],
                'unique_together': {('template_type', 'name')},
            },
        ),
        migrations.AddField(
            model_name='smshistory',
            name='template_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to='appointments.smstemplate'),
        ),
    ]
