# Generated by Django 5.2.1 on 2025-11-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_smstemplate_smshistory_template_used'),
    ]

    operations = [
        # Removed RemoveField operations for 'archived' - these fields never existed
        migrations.AlterField(
            model_name='smstemplate',
            name='template_type',
            field=models.CharField(choices=[('confirmation', 'Appointment Confirmation'), ('reminder', 'Appointment Reminder'), ('cancellation', 'Cancellation Notification'), ('package_confirmation', 'Package Confirmation'), ('attendant_reassignment', 'Attendant Reassignment'), ('custom', 'Custom Template')], max_length=30),
        ),
    ]
