# Generated by Django 5.2.8 on 2025-11-14 03:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_remove_closedday_archived_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='attendant_rating',
            field=models.IntegerField(blank=True, help_text='Rating from 1 to 5 stars for attendant', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(help_text='Rating from 1 to 5 stars for appointment', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
