# Generated by Django 5.2.8 on 2025-11-14 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_feedback_attendant_rating_alter_feedback_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('appointment', 'Appointment'), ('package', 'Package'), ('confirmation', 'Confirmation'), ('cancellation', 'Cancellation'), ('reschedule', 'Reschedule'), ('system', 'System')], max_length=15),
        ),
        migrations.CreateModel(
            name='AttendantUnavailabilityRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Reason for unavailability (e.g., sick leave)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Patient Response'), ('resolved', 'Resolved')], default='pending', max_length=10)),
                ('patient_choice', models.CharField(blank=True, choices=[('choose_another', 'Choose Another Attendant'), ('reschedule_same', 'Reschedule with Same Attendant'), ('cancel', 'Cancel Appointment')], max_length=20, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailability_requests', to='appointments.appointment')),
            ],
            options={
                'db_table': 'attendant_unavailability_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
