# Generated by Django 5.2.8 on 2025-11-14 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_alter_notification_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('add', 'Add'), ('edit', 'Edit'), ('archive', 'Archive')], max_length=10)),
                ('item_type', models.CharField(choices=[('service', 'Service'), ('product', 'Product'), ('package', 'Package')], max_length=10)),
                ('item_id', models.IntegerField()),
                ('item_name', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional details about the action')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'History Log',
                'verbose_name_plural': 'History Logs',
                'db_table': 'history_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
