# Generated by Django 5.2.1 on 2025-11-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0011_historylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historylog',
            name='action_type',
            field=models.CharField(choices=[('add', 'Add'), ('edit', 'Edit'), ('archive', 'Archive'), ('book', 'Book'), ('confirm', 'Confirm'), ('cancel', 'Cancel'), ('complete', 'Complete'), ('reschedule', 'Reschedule'), ('reject', 'Reject'), ('approve', 'Approve')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historylog',
            name='item_type',
            field=models.CharField(choices=[('service', 'Service'), ('product', 'Product'), ('package', 'Package'), ('appointment', 'Appointment'), ('cancellation_request', 'Cancellation Request'), ('reschedule_request', 'Reschedule Request')], max_length=20),
        ),
    ]
