# Generated by Django 5.2.1 on 2025-11-26 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0012_update_history_log_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cancellationrequest',
            name='reason',
            field=models.TextField(blank=True, help_text='Reason for cancellation (required when cancelling)', null=True),
        ),
        # Skip AlterUniqueTogether if index already exists - handled manually if needed
        # migrations.AlterUniqueTogether(
        #     name='feedback',
        #     unique_together={('appointment', 'patient')},
        # ),
        # RescheduleRequest model - skip if table already exists
        # migrations.CreateModel(
        #     name='RescheduleRequest',
        #     fields=[...],
        # ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_date', models.DateField()),
                ('treatment_time', models.TimeField()),
                ('notes', models.TextField(blank=True, help_text='Treatment notes and observations', null=True)),
                ('next_appointment_recommended', models.DateField(blank=True, help_text='Recommended date for next appointment', null=True)),
                ('products_used', models.TextField(blank=True, help_text='Products used during treatment', null=True)),
                ('duration_minutes', models.IntegerField(blank=True, help_text='Actual treatment duration in minutes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='treatment', to='appointments.appointment')),
            ],
            options={
                'verbose_name': 'Treatment',
                'verbose_name_plural': 'Treatments',
                'db_table': 'treatments',
                'ordering': ['-treatment_date', '-treatment_time'],
            },
        ),
    ]
