# Generated by Django 5.2.8 on 2025-11-27 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0015_alter_appointment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('appointment', 'Appointment'), ('pre-order', 'Pre-Order'), ('package', 'Package'), ('confirmation', 'Confirmation'), ('cancellation', 'Cancellation'), ('reschedule', 'Reschedule'), ('system', 'System')], max_length=15),
        ),
    ]
